# Generated by Django 3.2.8 on 2022-10-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('storeId', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.IntegerField()),
                ('identifier', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
