# Generated by Django 3.2.8 on 2022-10-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signscloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brandId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('dealId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('store', models.IntegerField()),
                ('image', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
